#!/bin/bash

if [ "$EUID" -ne 0 ]
then   
    echo "Please run with sudo"
    exit
fi

desktopDir="/home/$(echo $(pwd) | sed "s|/home/||" | sed -r "s|/.+||")/Desktop"
installed=$(dnf list installed)

#Dependency for the program's GUI
if ! echo $installed | grep -qi "newt"; then
    dnf install newt -y
fi
if ! echo $installed | grep -qi "clamav"; then
    dnf install clamav -y
fi
if ! echo $installed | grep -qi "net-tools"; then
    dnf install net-tools -y
fi
if ! echo $installed | grep -qi "rkhunter"; then
    dnf install rkhunter -y
fi
if ! echo $installed | grep -qi "chkrootkit"; then
    dnf install chkrootkit -y
fi
if ! echo $installed | grep -qi "aide"; then
    dnf install aide -y
fi

whiptail --msgbox \
'
             Welcome To
    ______ _     _   _____________ 
    |  ___| |   | | | |  ___|  ___|
    | |_  | |   | | | | |_  | |_   
    |  _| | |   | | | |  _| |  _|  
    | |   | |___| |_| | |   | |    
    \_|   \_____/\___/\_|   \_|   
Faith Lutheran Ubuntu & Fedora Fricker' 16 42

whiptail --msgbox \
"Before proceeding, please make sure that you have completed the forensics or that running things here won't mess with any of the forensics questions. Also, duh, read the README first." 12 42

touch $desktopDir/fluff.log

echo "
---------------------------------------------------------------------
New startup of FLUFF
---------------------------------------------------------------------
" >> $desktopDir/fluff.log

cd core

while true
do
    CHOICE=$(
    whiptail --title "What would you like to run?" --menu "" 12 50 5 \
        "1)" "Run updates."   \
        "2)" "Scans."  \
        "3)" "Change user passwords." \
        "4)" "Policies." \
        "X)" "Quit." 3>&2 2>&1 1>&3	
    )

    case $CHOICE in
        "1)")
            ./updates.sh   $desktopDir
        ;;
        "2)")   
            ./scans.sh     $desktopDir
        ;;
        "3)")   
            ./passwords.sh $desktopDir
        ;;
        "4)")   
            ./policies.sh  $desktopDir
        ;;
        "X)")
            cd ..
            exit
        ;;
    esac
done
