gsettings set org.gnome.desktop.session idle-delay 300
gsettings set org.gnome.desktop.screensaver lock-enabled true
gsettings set com.canonical.unity.desktop.screensaver show-notifications true
gsettings set com.ubuntu.SoftwareProperties ubuntu-pro-banner-visible false
gsettings set com.ubuntu.touch.system activity-timeout 300
gsettings set com.ubuntu.update-notifier end-system-uids 999
gsettings set com.ubuntu.update-notifier end-system-uids 999
gsettings set com.ubuntu.update-notifier no-show-notifications false
gsettings set com.ubuntu.update-notifier regular-auto-launch-interval 1
gsettings set com.ubuntu.update-notifier show-apport-crashes true
gsettings set com.ubuntu.update-notifier show-livepatch-status-icon true
gsettings set org.freedesktop.miner.files low-disk-space-limit 95
gsettings set org.gnome.control-center show-development-warning true
gsettings set org.gnome.desktop.screensaver lock-delay 300
gsettings set org.gnome.desktop.screensaver user-password-required true
gsettings set org.gnome.login-screen disable-user-list true