#!/bin/bash

if [ "$EUID" -ne 0 ]
then   
    echo "Please run with sudo"
    exit
fi

desktopDir="/home/$(echo $(pwd) | sed "s|/home/||" | sed -r "s|/.+||")/Desktop"

#Dependency for the program's GUI
apt install whiptail -y

apt install clamav -y
apt install net-tools -y
apt install rkhunter -y
apt install chkrootkit -y
apt install aide -y


whiptail --msgbox \
'
             Welcome To
  ______ _      _   _  _____  _   _ 
  |  ___| |    | | | |/  ___|| | | |
  | |_  | |    | | | |\ `--. | |_| |
  |  _| | |    | | | | `--. \|  _  |
  | |_  | |____| |_| |/\__/ /| | | |
  \_(_) \_____(_)___(_)____(_)_| |_/

Faith Lutheran Ubuntu Security Helper' 16 42

whiptail --msgbox \
"Before proceeding, please make sure that you have completed the forensics or that running things here won't mess with any of the forensics questions. Also, duh, read the README first. Also, before running password policies, open a window using sudo su, your image WILL brick." 12 42

touch $desktopDir/flush.log

echo "
---------------------------------------------------------------------
New startup of FLUSH
---------------------------------------------------------------------
" >> $desktopDir/flush.log

cd core

while true
do
    CHOICE=$(
    whiptail --title "What would you like to run?" --menu "" 12 50 5 \
        "1)" "Run updates."   \
        "2)" "Scans."  \
        "3)" "Change user passwords." \
        "4)" "Policies." \
        "X)" "Quit." 3>&2 2>&1 1>&3	
    )

    case $CHOICE in
        "1)")
            ./updates.sh   $desktopDir
        ;;
        "2)")   
            ./scans.sh     $desktopDir
        ;;
        "3)")   
            ./passwords.sh $desktopDir
        ;;
        "4)")   
            ./policies.sh  $desktopDir
        ;;
        "X)")
            cd ..
            exit
        ;;
    esac
done